//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 09:54:31 PM EET 
//


package spring_advance.wsmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wsUser" type="{http://spring-advance/wsmodel}wsUser" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsUser"
})
@XmlRootElement(name = "getUserByIdResponse")
public class GetUserByIdResponse {

    protected WsUser wsUser;

    /**
     * Gets the value of the wsUser property.
     * 
     * @return
     *     possible object is
     *     {@link WsUser }
     *     
     */
    public WsUser getWsUser() {
        return wsUser;
    }

    /**
     * Sets the value of the wsUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsUser }
     *     
     */
    public void setWsUser(WsUser value) {
        this.wsUser = value;
    }

}
