//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 09:54:31 PM EET 
//


package spring_advance.wsmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the spring_advance.wsmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: spring_advance.wsmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdResponse }
     * 
     */
    public GetUserByIdResponse createGetUserByIdResponse() {
        return new GetUserByIdResponse();
    }

    /**
     * Create an instance of {@link WsUser }
     * 
     */
    public WsUser createWsUser() {
        return new WsUser();
    }

    /**
     * Create an instance of {@link GetUserByEmailResponse }
     * 
     */
    public GetUserByEmailResponse createGetUserByEmailResponse() {
        return new GetUserByEmailResponse();
    }

    /**
     * Create an instance of {@link GetUsersByNameRequest }
     * 
     */
    public GetUsersByNameRequest createGetUsersByNameRequest() {
        return new GetUsersByNameRequest();
    }

    /**
     * Create an instance of {@link SaveNewUserResponse }
     * 
     */
    public SaveNewUserResponse createSaveNewUserResponse() {
        return new SaveNewUserResponse();
    }

    /**
     * Create an instance of {@link GetAllEventsRequest }
     * 
     */
    public GetAllEventsRequest createGetAllEventsRequest() {
        return new GetAllEventsRequest();
    }

    /**
     * Create an instance of {@link SaveNewUserRequest }
     * 
     */
    public SaveNewUserRequest createSaveNewUserRequest() {
        return new SaveNewUserRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdRequest }
     * 
     */
    public GetUserByIdRequest createGetUserByIdRequest() {
        return new GetUserByIdRequest();
    }

    /**
     * Create an instance of {@link GetUserByEmailRequest }
     * 
     */
    public GetUserByEmailRequest createGetUserByEmailRequest() {
        return new GetUserByEmailRequest();
    }

    /**
     * Create an instance of {@link GetUsersByNameResponse }
     * 
     */
    public GetUsersByNameResponse createGetUsersByNameResponse() {
        return new GetUsersByNameResponse();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse }
     * 
     */
    public GetAllEventsResponse createGetAllEventsResponse() {
        return new GetAllEventsResponse();
    }

    /**
     * Create an instance of {@link WsEvent }
     * 
     */
    public WsEvent createWsEvent() {
        return new WsEvent();
    }

    /**
     * Create an instance of {@link WsAuditorium }
     * 
     */
    public WsAuditorium createWsAuditorium() {
        return new WsAuditorium();
    }

}
